theme: minima

title: WAVESTORMS
description: description
skin: auto

# Navigation menu
header_pages:
  - index.md
  - about.md
  - members.md
  - research.md
  - publications.md

show_excerpts: true 
