theme: minima

title: WAVESTORMS
# description: description
skin: auto

# Navigation menu
nav_pages:
  # - index.md
  - about.md
  - members.md
  - research.md
  - publications.md
  - gallery.md

collections:
  gallery:
    output: true


show_excerpts: true 

social_links:
  - title: WAVESTORMS at GitHub
    icon: github
    url: "https://github.com/wavestorms"
